version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 29017:27017
    volumes:
      - /oyiyio/volumes/nest-practice:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: nest

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8092:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: material
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: nest
      ME_CONFIG_MONGODB_URL: mongodb://test:nest@mongo:27017/
